# Upload avatar
POST http://localhost:3500/api/files/upload/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="avatar"; filename="avatar.jpg"
Content-Type: image/jpeg

< ../../../assets/avatar.jpg

--boundary--

###

# Upload photo
POST http://localhost:3500/api/files/upload/photo HTTP/1.1
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="photo"; filename="picture.jpg"
Content-Type: image/jpeg

< ../../../assets/picture.jpg

--boundary--

###

# Get file by ID
GET http://localhost:3500/api/files/659f379fbe5e14fe8d4abb42 HTTP/1.1

###
