#Создание нового комментария

POST http://localhost:3000/api/publics/75a10f99-92b1-4617-adc2-59d1316a999f/comments HTTP/1.1
Content-Type: application/json

{
  "userId":"123",
  "text":"Comment text"
}

###

#Получение комментариев публикации

GET http://localhost:3000/api/publics/8a1af1cc-308f-436f-8585-9502431a6a29/comments HTTP/1.1
Content-Type: application/json

###

#Удаление комментария по ID

DELETE http://localhost:3000/api/publics/75a10f99-92b1-4617-adc2-59d1316a999f/comments/fbe79fc3-3173-4da9-b9ea-802e916f0387 HTTP/1.1
Content-Type: application/json

###
