#Создание новой публикации

POST http://localhost:3000/api/publics HTTP/1.1
Content-Type: application/json

{
  "userId": "658170cbb954e9f5b905ccf4",
  "isRepost": false,
  "header": "Выбранный нами инновационный путь",
  "notice": "Новый закон накладывает вето на детский заливистый смех",
  "text": "Безусловно, сплочённость команды профессионалов способствует повышению качества экспериментов, поражающих по своей масштабности и грандиозности.",
  "tags": [],
  "publicType": "text",
  "publicStatus": "posted"
}

###

#Получение публикации по ID

GET http://localhost:3000/api/publics/598b72f1-5500-44c4-8159-c0e827923312 HTTP/1.1
Content-Type: application/json

###

#Изменение публикации по ID

PATCH http://localhost:3000/api/publics/222ffb54-7f04-4416-9030-35857116905b HTTP/1.1
Content-Type: application/json

{
  "userId": "658170cbb954e9f5b905ccf4",
  "isRepost": true,
  "header": "Выбранный нами инновационный путь не стал ограничивающим фактором",
  "notice": "Новый закон накладывает вето на детский заливистый смех",
  "text": "Безусловно, сплочённость команды профессионалов способствует повышению качества экспериментов, поражающих по своей масштабности и грандиозности.",
  "tags": [],
  "publicType": "text",
  "publicStatus": "posted"
}

###

#Удаление публикации по ID

DELETE http://localhost:3000/api/publics/a348d306-ee77-4cd9-8df7-aa1ec901b00e HTTP/1.1
Content-Type: application/json

###

#Получение всех публикаций
GET http://localhost:3000/api/publics HTTP/1.1

###

#Получение публикаций с пагинацией
GET http://localhost:3000/api/publics?limit=2&sortDirection=desc HTTP/1.1

###

#Получение публикаций определенного пользователя
GET http://localhost:3000/api/publics?userId=658170cbb954e9f5b905ccf4 HTTP/1.1

###

#Получение публикаций определенного типа
GET http://localhost:3000/api/publics?publicType=photo HTTP/1.1

###

#Получение черников публикаций для авторизованного пользователя
GET http://localhost:3000/api/publics?publicStatus=draft HTTP/1.1

###

#Получение черников публикаций по тегу
GET http://localhost:3000/api/publics?tag=Комиксы HTTP/1.1

