#Создание нового пользователя

POST http://localhost:3333/api/user/register HTTP/1.1
Content-Type: application/json

{
  "email":"user10@yandex.com",
  "name":"July",
  "password":"12345678"
}

###

#Получение информации о пользователе по ID
GET http://localhost:3333/api/user/65b8e86fbe313fcda54da97a HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NWI4OGM1Y2NhYjM1YWM5ODRjODM1YjQiLCJlbWFpbCI6InVzZXJAeWFuZGV4LmNvbSIsIm5hbWUiOiJKdWx5IiwiaWF0IjoxNzA2NTkzNDE1LCJleHAiOjE3MDY2Nzk4MTV9.uouP17pKbM3kfnmUEyF4O3ijxv22BO1yzYC3frryWaY

###

#Авторизация пользователя по email и password
POST http://localhost:3333/api/user/login HTTP/1.1
Content-Type: application/json

{
  "email":"user7@gmail.com",
  "password":"12345678"
}

###

#Смена пароля пользователя
PUT http://localhost:3333/api/user/change-password HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NWI4OGM1Y2NhYjM1YWM5ODRjODM1YjQiLCJlbWFpbCI6InVzZXJAeWFuZGV4LmNvbSIsIm5hbWUiOiJKdWx5IiwiaWF0IjoxNzA2NTkzNDE1LCJleHAiOjE3MDY2Nzk4MTV9.uouP17pKbM3kfnmUEyF4O3ijxv22BO1yzYC3frryWaY

{
  "oldPassword": "12345678",
  "newPassword":"1234568",
  "id":"65b88c5ccab35ac984c835b4"
}

###

# Получение новой пары JWT
POST http://localhost:3333/api/user/refresh HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NWI4OGM1Y2NhYjM1YWM5ODRjODM1YjQiLCJlbWFpbCI6InVzZXJAeWFuZGV4LmNvbSIsIm5hbWUiOiJKdWx5IiwidG9rZW5JZCI6IjMzZmM3ZTcxLWFlNGMtNDA0Ni1iNzE3LTc0NTE2MjYzMzNjYyIsImlhdCI6MTcwNjU5MzQ3MywiZXhwIjoxNzA2NTkzNTMzfQ.i7ZScCCQr7dY11rScxs2KUhLEBDyd5FZDBsepHg4VMI

###

# Подписаться на пользователя
PUT  http://localhost:3333/api/user/subscribe/65b8ddf0abfd07b1655e6091 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NWI4ZTg2ZmJlMzEzZmNkYTU0ZGE5N2EiLCJlbWFpbCI6InVzZXI3QGdtYWlsLmNvbSIsIm5hbWUiOiJKb2huIiwiaWF0IjoxNzA2NjMzMTI3LCJleHAiOjE3MDY3MTk1Mjd9.x6WKKOrouKbwU8btMRqaqMKgSggyOxFupO-kMX9G58Q

###

# Отписаться от пользователя
PUT  http://localhost:3333/api/user/unsubscribe/65b5fe2920ce43f24e384de7 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NWI2MThiYjIwY2U0M2YyNGUzODRkZjgiLCJlbWFpbCI6InVzZXIxQGdtYWlsLmNvbSIsIm5hbWUiOiJKb2huIiwiaWF0IjoxNzA2NjA1NDA3LCJleHAiOjE3MDY2OTE4MDd9.y75GNMBq8ljRybGmjGTEsdhBZKBziSFYe3mbsUduZHI
